<partial-result>
  <partial-style-import>
    @yield('style-import')
  </partial-style-import>
  <partial-style>
    @yield('style')
  </partial-style>
  <partial-body>
    @yield('body')
  </partial-body>
  <partial-script>
    @yield('script')
  </partial-script>
</partial-result>
