image: php:7.0

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -y
  - apt-get install -y git
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

PHPLint:
  script:
    - vendor/bin/phpcs --standard=PSR2 app/
