image: php:7.0-cli

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

PHPLint:
  script:
    - php vendor/squizlabs/php_codesniffer/scripts/phpcs --standard=PSR2 app/
    - php vendor/bin/phpcs --standard=PSR2 app/
